### ISSUE TITLE
App Action works when testing with plugin but not when called via voice with Google Assistant 

### ISSUE THREAD

**Issue by Polar-Points** [actions-on-google/appactions-fitness-kotlin#4]
Hey again!

My app action works when tested with the app action plugin in Android Studio. But I am not able to get it working via voice in google assistant. I have made a draft and uploaded onto the google play store, made sure my android studio account, my account that is connected to the assistant and the account on my developer account are the same ones. Is there something obvious that I am missing?

Thanks!

**Comment by adamkoch** [comment]
Hi, please see this SO post to see if it helps:
https://stackoverflow.com/a/56143392/268156

If this doesn't help, please open a new SO question (tag "app-actions"). The issue tracker is more for issues with the sample app.

Thanks!

**Comment by skimarxall** [comment]
Hi,

If you managed to make the action working with the plugin then the voice should work with the right wording. Check @adamkoch link to StackOverflow

Just as an extra clarification:

- Make sure you are saying the preview name you set when opening the plugin, if you let it empty then the plugin uses the app name. (i.e Hey Google, .... with/in/on My App)
- Try writing instead of speaking
- If you did not modify the sample actions.xml "Hey Google, start running in Fit Actions" should definitely work

**Comment by Polar-Points** [comment]
Cool, I will take a look at that. Thank you!
