### ISSUE TITLE
I get an error when trying to upload the generated aab file in Google Play

### ISSUE THREAD

**Issue by vdaele** [actions-on-google/appactions-fitness-kotlin#5]
When trying to upload the aab file to Google Play store I get the following error

"You uploaded an APK or Android App Bundle which specifies an actions schema document in its manifest, but action schemas are not yet allowed. If you are part of a beta program, you need to have your developer account whitelisted."

Can I whitelist my account myself or is this something you have to do somehow?

**Comment by adamkoch** [comment]
That's because App Actions is not yet launched for consumers, only for developers. Once it's available for consumers Google Play Store will start accepting apps with actions.xml files. In meantime, you can comment out the meta-data tag in your manifest pointing to your actions.xml to ensure your app can be uploaded to Play Console as normal.

Also, to be part of the first App Actions that go live to consumers, you should fill out this form:
https://developers.google.com/actions/appactions/deployment-request

**Comment by vdaele** [comment]
I'm a bit confused: the readme states "Application published in Google Play console (at least as draft)" so I built the example app and uploaded it to Google Play (which failed with the above error).
Or should I have a (dummy) application in Google Play without App Actions and use that packageName for this example app?

On a related note: when I try to login in Android Studio and selecting my account, my browser opens with a url starting with https://localhost:47341/Callback but shows an error (both on Chrome and on Opera)
![image](https://user-images.githubusercontent.com/10400082/58411375-73456480-8074-11e9-81bb-2acf9c0e73c1.png)
(I'm on Ubuntu 16.04)

**Comment by adamkoch** [comment]
> Or should I have a (dummy) application in Google Play without App Actions and use that packageName for this example app?

Yes this ^^.

Sorry it's a bit confusing. In order to test out App Actions (using the Test Tool) you must at least have a draft APK (or AAB) in Google Play Console (to prove your ownership of that package name). This draft can be any version of your app (even a non-working of your app) but as you found, it shouldn't (and can't) include an actions.xml linked in your manifest at this time.

As for the Studio login, you will need to file a issue with the Studio team here:
https://developer.android.com/studio/report-bugs

Although I don't see that problem myself (using Chrome on Mac). I believe the way OAuth works in this case is it's bouncing the token off a local web server which is why you see localhost in the address bar. I'm not sure how this works with https though.

**Comment by vdaele** [comment]
Thanks for the clarification!

**Comment by AndroidDeveloperLB** [comment]
For some reason I get this message, yet I don't use any actions file. How come?
